server:
  port: 9090
  
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  data:
    mongodb:
      host: mongo-container
      port: 27017
      database: Merchants
  main:
    allow-circular-references: true
#spring:
#  datasource:
##    url: jdbc:mysql://localhost:3306/user_service
##    username: root
##    password: pass@word1
#    url: jdbc:mysql://rds-demo.c2ozhw4mlwdz.us-east-1.rds.amazonaws.com:3306/user_service
#    username: admin
#    password: admin1234
#  jpa:
#    hibernate:
#      ddl-auto: update
#  main:
#    allow-circular-references: true
#  application:
#    name: USER-SERVICE
#book:
#  unsubscribe:
#    duration:
#      hours: 24