version: 0.2


phases:
  pre_build:
    commands:
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 527488999673.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t merchant-service .
      - docker tag merchant-service:latest 527488999673.dkr.ecr.us-east-1.amazonaws.com/merchant-service:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 527488999673.dkr.ecr.us-east-1.amazonaws.com/merchant-service:latest
      - echo Writing image definitions file...
      - printf '[{"name":"Merchant-Service","imageUri":"527488999673.dkr.ecr.us-east-1.amazonaws.com/merchant-service:latest"}]' > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
   - imagedefinitions.json
   - target/Merchant-Service.jar